version: "2.1"

services:
  powerdns-admin:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: powerdns-admin
    mem_limit: 256M
    memswap_limit: 256M
    ports:
      - "8181:8181"
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - default
    environment:
      DBBACKEND: mysql
      PDNS_ADMIN_PDNS_VERSION: '4.1.1'
      PDNS_ADMIN_PDNS_API_KEY: someapikey
      PDNS_ADMIN_SIGNUP_ENABLED: "False"
      PDNS_ADMIN_SQLA_DB_USER: pdnsadmin
      PDNS_ADMIN_SQLA_DB_NAME: pdnsadmin
      PDNS_ADMIN_SQLA_DB_PASSWORD: somepassword
      PDNS_ADMIN_SQLA_DB_HOST: powerdns-admin-mysql
    depends_on:
      powerdns-admin-mysql:
        condition: service_healthy

  powerdns-admin-mysql:
    image: mysql/mysql-server:5.7
    container_name: powerdns-admin-mysql
    mem_limit: 256M
    memswap_limit: 256M
    ports:
      - "3306:3306"
    networks:
      - default
    environment:
      - MYSQL_DATABASE=pdnsadmin
      - MYSQL_USER=pdnsadmin
      - MYSQL_PASSWORD=somepassword
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  pdns-server:
    image: psitrax/powerdns
    hostname: pdns
    ports:
      - "53:53"
    networks:
      - default
    command: --api=yes --api-key=someapikey --webserver-address=0.0.0.0 --webserver-allow-from=0.0.0.0/0
    environment:
      - MYSQL_HOST=pdns-mysql
      - MYSQL_USER=pdns
      - MYSQL_PASS=somepassword
      - PDNS_API_KEY=someapikey
      - PDNS_WEBSERVER_ALLOW_FROM=0.0.0.0/0
    depends_on:
      pdns-mysql:
        condition: service_healthy

  pdns-mysql:
    image: mysql/mysql-server:5.7
    mem_limit: 256M
    memswap_limit: 256M
    ports:
      - "3307:3306"
    networks:
      - default
    environment:
      - MYSQL_DATABASE=pdns
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD=somepassword
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

networks:
  default:

volumes:
  powerdns-mysql-data: